#docker-compose -f keycloak.stack.yml up -d
version: '3.1'

services:
  #user: postgres mdp: POSTGRES_PASSWORD
  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Keycloak@2022
    ports:
      - 8080:8080
    networks:
      - localNetwork

networks:
  localNetwork:
    driver: bridge